config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users, only: [:show] do
    get 'followings' => "users#followings"
    get 'followers' => "users#followers"
    get 'fav_tweets' => "users#fav_tweets"
  end
  
  resources :users
  resources :microposts
  post "microposts/retweet"
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :fav_relationships, only: [:create, :destroy]
end

app/models/fav_relationship.rb
class FavRelationship < ActiveRecord::Base
  belongs_to :user
  belongs_to :fav_tweet, :class_name => "Micropost", :foreign_key => "fav_tweet_id"
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  belongs_to :retweet_from, class_name: "Micropost"
  has_many :retweets, :class_name => "Micropost", :foreign_key => "retweet_from_id"
  
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }, if: "retweet_from_id.nil?"
  validates_uniqueness_of :retweet_from_id, :scope => :user_id, unless: "retweet_from_id.nil?"
  
  mount_uploader :image, ImageUploader
  
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase } 
    validates :name, presence: true, length: { maximum:50 }
    validates :location, presence: true, length: { maximum: 50 }
    validates :profile, presence: true, length: { maximum: 150 }
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, 
              format: {with: VALID_EMAIL_REGEX },
              uniqueness: { case_sensitive: false }
              
    has_secure_password
    
    has_many :microposts
    has_many :following_relationships, class_name: "Relationship",
                                       foreign_key: "follower_id",
                                       dependent: :destroy
    has_many :following_users, through: :following_relationships, source: :followed
    
    has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
    has_many :follower_users, through: :follower_relationships, source: :follower
    
    has_many :fav_relationships
    has_many :fav_tweets, :class_name => "Micropost", :foreign_key => "fav_tweet_id", through: :fav_relationships
    
  # follow and unfollow
  def follow(other_user)
    following_relationships.create(followed_id: other_user.id)
  end
  
  def unfollow(other_user)
    following_relationships.find_by(followed_id: other_user.id).destroy
  end
  
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  # timeline
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
  
  # fav_tweets
  def fav_tweet(micropost)
    fav_relationships.create(fav_tweet_id: micropost.id)
  end
  
  def remove_fav_tweet(micropost)
    fav_relationships.find_by(fav_tweet_id: micropost.id).destroy
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/fav_relationships_controller.rb
class FavRelationshipsController < ApplicationController
    before_action :logged_in_user
  
  def create
    @micropost = Micropost.find(params[:fav_tweet_id])
    current_user.fav_tweet(@micropost)
    flash[:success] = "お気に入りに追加しました!"
    redirect_to root_url
  end
  
  def destroy
   @micropost = Micropost.find(params[:fav_tweet_id])
   current_user.remove_fav_tweet(@micropost)
   flash[:success] = "お気に入りから削除しました"
   redirect_to root_url
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create]
    
    def create
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc).page( params[:page]).per(10)
      @micropost = current_user.microposts.build(micropost_params)
      if @micropost.save
        flash[:success] = "Micropost created!"
        redirect_to root_url
      else
        render 'static_pages/home'
      end
    end
    
    def retweet
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc).page( params[:page]).per(10)
      @micropost = current_user.microposts.build(micropost_params)
      if @micropost.save
        flash[:success] = "Micropost created!"
        redirect_to root_url
      else
        render 'static_pages/home'
      end
    end
    
    def destroy
      @micropost = current_user.microposts.find_by(id: params[:id])
      return redirect_to root_url if @micropost.nil?
      @micropost.destroy
      flash[:success] = "Micropost deleted"
      redirect_to request.referrer || root_url
    end
    
    private
    def micropost_params
      params.require(:micropost).permit(:content, :image, :retweet_from_id)
    end
    
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user
  
  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
  end
  
  def destroy
    @user = current_user.following_relationships.find(params[:id]).followed
    current_user.unfollow(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to root_url
    else
      flash[:danger] = 'invalid email/password confirmation'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @micropost = current_user.microposts.build if logged_in?
    @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc).page( params[:page]).per(10) if logged_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:followings, :followers, :edit, :update]
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to @user, notice: 'ユーザー情報を編集しました。'
    else
      render 'edit'
    end
  end
  
  def followings
    @user = User.find(params[:user_id])
    @followings = @user.following_users
  end
  
  def followers
    @user = User.find(params[:user_id])
    @followers = @user.follower_users
  end
  
  def fav_tweets
    @user = User.find(params[:user_id])
    @fav_tweets = @user.fav_tweets
  end
  
  private
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :location, :url, :profile)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
  
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/
#{gravatar_id}
?s=
#{size}
"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Microposts", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Home",   '#' %>
        </li>
        <li>
          <%= link_to "Help",   '#' %>
        </li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle"  data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Profile", current_user %>
              </li>
              <li>
                <%= link_to "Settings", edit_user_path(current_user) %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
        <li>
          <%= link_to "Log in", login_path %>
        </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microposts</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message|  %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-
  <%= micropost.id %>
  ">
  
  <% if micropost.retweet_from_id.present? %> <!-- retweetの場合 -->
    <div class="alert alert-info">
      <%= micropost.user.name%>
      さんがリツイートしました。
    </div>
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.retweet_from.user %>
    <span class="user">
      <%= link_to micropost.retweet_from.user.name, micropost.retweet_from.user %>
    </span>
    <span class="content">
      <%= micropost.retweet_from.content %>
    </span>
      <%= image_tag micropost.retweet_from.image.url, class:"img-responsive" %>
    <span class="timestamp">
      Posted 
      <%= time_ago_in_words(micropost.retweet_from.created_at) %>
      前
    </span>
    
  <% else %> <!-- retweetではない普通のmicropostの場合 -->
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
    
    <span class="user">
      <%= link_to micropost.user.name, micropost.user %>
    </span>
    <span class="content">
      <%= micropost.content %>
    </span>
      <%= image_tag micropost.image.url, class:"img-responsive" %>
    <span class="timestamp">
      Posted 
      <%= time_ago_in_words(micropost.created_at) %>
      前
      <% if current_user == micropost.user %>
        <%= link_to "delete", micropost, method: :delete, data: { confirm: "You sure?" } %>
      <% else %>
        <% unless current_user.microposts.where(retweet_from_id: micropost.id).present? %>
          <%= form_for(@micropost, :url => {:controller => "microposts",  :action => 'retweet'}) do |f| %>
            <%= f.hidden_field :retweet_from_id ,value: micropost.id %>
            <%= f.submit "retweet", class:"btn btn-xs btn-info" %>
          <% end %>
        <% else%>
          <%= form_for(@micropost, :url => {:controller => "microposts",  :action => 'retweet'}) do |f| %>
            <%= f.hidden_field :retweet_from_id ,value: micropost.id %>
            <%= f.submit "already retweet", class:"btn btn-xs btn-info", disabled: true %>
          <% end %>
        <% end %>
      <% end %>
    </span>
    <div id="fav_relationship_<%= micropost.id %>">
      <%= render partial: "users/fav_relationship", locals: { micropost: micropost } %>
    </div>
  <% end %>
</li>

app/views/relationships/create.js.erb
$("#follow_form_<%= @user.id %>").html(
    "<%=escape_javascript(render partial: 'users/unfollow', locals: { user: @user })%>"
  );

app/views/relationships/destroy.js.erb
$("#follow_form_<%= @user.id %>").html(
    "<%=escape_javascript(render partial: 'users/follow', locals: { user: @user })%>"
  );

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains 
        <%= pluralize(object.errors.count, "error") %>
.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
    
    <% end %>

    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if feed_items.any? %>
  <ol class="microposts">
    <%= render feed_items %>
  </ol>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    <%= f.file_field :image, class:"form-control" %>
  </div>
  
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>

<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
      <div class="row">
        <div class="col-md-4">
          <%= link_to user_followings_path(current_user) do %>
            <div class="panel panel-primary text-center">
              <div class="panel-heading">
                <h3 class="panel-title">following</h3>
              </div>
              <div class="panel-body">
                <%= current_user.following_users.size %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-md-4">
          <%= link_to user_followers_path(current_user) do %>
            <div class="panel panel-primary text-center">
              <div class="panel-heading">
                <h3 class="panel-title">follower</h3>
              </div>
              <div class="panel-body">
                <%= current_user.follower_users.size %>
              </div>
            </div>
          <% end %>
        </div>
         <div class="col-md-4">
          <%= link_to user_fav_tweets_path(current_user) do %>
            <div class="panel panel-primary text-center">
              <div class="panel-heading">
                <h3 class="panel-title">fav</h3>
              </div>
              <div class="panel-body">
                <%= current_user.fav_tweets.size %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <div id="time_line">
        <%= render partial: 'shared/feed', locals: { feed_items: @feed_items } %>
      </div>
      <div>
        <%= paginate(@feed_items) %>
      </div>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Microposts</h1>
    <%= link_to "Sign up now!", signup_path, class:"btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/users/_fav_relationship.html.erb
<% if current_user.fav_relationships.where(fav_tweet_id: micropost.id).present? %>
  <%= form_for(current_user.fav_relationships.find_by(fav_tweet_id: micropost.id), html: { method: :delete}) do |f| %>
    <%= hidden_field_tag :fav_tweet_id, micropost.id %>
    <%= f.submit "お気に入りから削除", class: "btn btn-xs btn-danger" %>
  <% end %>
  
<% else %>
  <%= form_for(current_user.fav_relationships.build) do |f| %>
      <%= hidden_field_tag :fav_tweet_id, micropost.id %>
    <%= f.submit "お気に入り", class: "btn btn-xs btn-warning" %>
  <% end %>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div>
    <%= hidden_field_tag :followed_id, user.id %>
  </div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != user %>
  <div id="follow_form_<%= user.id %>">
    <% if current_user.following?(user) %>
      <%= render partial: 'unfollow', locals: { user: user } %>
    <% else %>
      <%= render partial: 'follow', locals: { user: user } %>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= f.label :location %>
      <%= f.select :location, [["日本", "Japan"], ["アメリカ", "America"], ["中国", "china"], ["韓国", "Korea"], ["オーストラリア", "Australia"], ["その他", "Other"]], :selected => "日本" %>
      <%= f.label :url %>
      <%= f.text_field :url, placeholder:"例：http://message-boardforkhsyukatu.herokuapp.com/" %>
      <%= f.label :profile %>
      <%= f.text_area :profile, placeholder:"150文字以内でご記入ください。" %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: user.id), html: { method: :delete }, remote:true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザー情報編集</h1>
<%= render 'form' %>

app/views/users/fav_tweets.html.erb
<h1><%= @user.name %>のお気に入り</h1>
<ol class="microposts">
  <%= render @fav_tweets %>
</ol>

app/views/users/followers.html.erb
<div class="row">
  <% @followers.each do |follower| %>
  <aside class="col-md-4">
    <%= link_to user_path(follower) do %>
    <section class="user_info">
      <h1>
        <%= gravatar_for follower %>
        <%= follower.name %>
      </h1>
    </section>
    <% end %>
    <%= render partial: 'follow_form', locals: { user: follower } %>
  </aside>
  <% end %>
</div>

app/views/users/followings.html.erb
<div class="row">
  <% @followings.each do |following| %>
  <aside class="col-md-4">
    <%= link_to user_path(following) do %>
    <section class="user_info">
      <h1>
        <%= gravatar_for following %>
        <%= following.name %>
      </h1>
    </section>
    <% end %>
    <%= render partial: 'follow_form', locals: { user: following } %>
  </aside>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <div class="row">
      <div class="col-md-6">
        <%= link_to user_followings_path(@user) do %>
          <div class="panel panel-primary text-center">
            <div class="panel-heading">
              <h3 class="panel-title">following</h3>
            </div>
            <div class="panel-body">
              <%= @user.following_users.size %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-md-6">
        <%= link_to user_followers_path(@user) do %>
          <div class="panel panel-primary text-center">
            <div class="panel-heading">
              <h3 class="panel-title">follower</h3>
            </div>
            <div class="panel-body">
              <%= @user.follower_users.size %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="panel panel-primary">
      <div class="panel-heading text-center">
        <h3 class="panel-title">User Profile</h3>
      </div>
      <div class="panel-body">
        Profile: <%= @user.profile %>
      </div>
      <div class="panel-body">
        Location: <%= @user.location %>
      </div>
      <div class="panel-body">
        Url: <%= link_to @user.url %>
      </div>
    </div>
    <p>
      <% if logged_in? %>
        <% if current_user == @user %>
          <%= link_to "編集する", edit_user_path(@user) %>
        <% end %>
      <% end %>
    </p>
  </aside>
  <div class="col-md-8">
    <% if logged_in? %>
      <%= render partial: 'follow_form', locals: { user: @user } %>
    <% end %>
    <% if @user.microposts.any? %>
      <h3><%= @user.microposts.count %></h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
    <% end %>
  </div>
</div>